FROM node:22-alpine AS builder
WORKDIR /app

ARG NEXT_PUBLIC_URL_API_BACKEND
ARG NEXT_PUBLIC_DNS_DOCKER_BACKEND

ENV NEXT_PUBLIC_URL_API_BACKEND=${NEXT_PUBLIC_URL_API_BACKEND}
ENV NEXT_PUBLIC_DNS_DOCKER_BACKEND=${NEXT_PUBLIC_DNS_DOCKER_BACKEND}

COPY ./frontend/package*.json ./
RUN npm ci

COPY ./frontend ./
RUN npm run build

RUN npm prune --omit=dev

FROM node:22-alpine AS runner
WORKDIR /app

ARG NEXT_PUBLIC_URL_API_BACKEND
ARG NEXT_PUBLIC_DNS_DOCKER_BACKEND

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000
ENV NEXT_PUBLIC_URL_API_BACKEND=${NEXT_PUBLIC_URL_API_BACKEND}
ENV NEXT_PUBLIC_DNS_DOCKER_BACKEND=${NEXT_PUBLIC_DNS_DOCKER_BACKEND}

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/next.config.* ./

EXPOSE 3000

CMD ["npm", "run", "start"]
